# Generated by Django 3.0.8 on 2020-07-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='xy',
            new_name='xyz',
        ),
    ]
